import type { Protocol } from "./types";

export const PROTOCOLS: Protocol[] = [
  {
    id: "uni",
    name: "Uniswap",
    symbol: "UNI",
    category: "DEX",
    networks: ["Ethereum", "Base", "Polygon"],
    tags: ["dex", "defi"],
    lat: 40.7128,
    lng: -74.006,
    logo: "/protocol-logos/uniswap.webp",
    description: "Automated liquidity and swap routing across EVM markets.",
    website: "https://uniswap.org",
  },
  {
    id: "ray",
    name: "Raydium",
    symbol: "RAY",
    category: "DEX",
    networks: ["Solana"],
    tags: ["dex", "solana"],
    lat: 1.3521,
    lng: 103.8198,
    logo: "/protocol-logos/raydium.webp",
    description: "Solana AMM and orderbook liquidity venue.",
    website: "https://raydium.io",
  },
  {
    id: "aave",
    name: "Aave",
    symbol: "AAVE",
    category: "Lending",
    networks: ["Ethereum", "Arbitrum", "Optimism"],
    tags: ["lending", "money-market"],
    lat: 51.5072,
    lng: -0.1276,
    logo: "/protocol-logos/aave.webp",
    description: "Collateralized liquidity markets for borrowing and lending.",
    website: "https://aave.com",
  },
  {
    id: "maker",
    name: "Sky",
    symbol: "SKY",
    category: "Stablecoin",
    networks: ["Ethereum"],
    tags: ["stablecoin", "governance"],
    lat: 55.6761,
    lng: 12.5683,
    logo: "/protocol-logos/makerdao.webp",
    description: "Decentralized credit and stablecoin infrastructure.",
    website: "https://sky.money",
  },
  {
    id: "jup",
    name: "Jupiter",
    symbol: "JUP",
    category: "DEX",
    networks: ["Solana"],
    tags: ["aggregator", "solana"],
    lat: 13.7563,
    lng: 100.5018,
    logo: "/protocol-logos/jupiter.webp",
    description: "Solana liquidity aggregation and routing engine.",
    website: "https://jup.ag",
  },
  {
    id: "curve",
    name: "Curve",
    symbol: "CRV",
    category: "DEX",
    networks: ["Ethereum", "Optimism", "Fantom"],
    tags: ["dex", "stable-swap"],
    lat: 46.2044,
    lng: 6.1432,
    logo: "/protocol-logos/curve.webp",
    description: "Stable asset exchange and liquidity incentives.",
    website: "https://curve.fi",
  },
  {
    id: "lido",
    name: "Lido",
    symbol: "LDO",
    category: "Staking",
    networks: ["Ethereum", "Polygon"],
    tags: ["staking", "liquid-staking"],
    lat: 52.52,
    lng: 13.405,
    logo: "/protocol-logos/lido.webp",
    description: "Liquid staking protocol for proof-of-stake networks.",
    website: "https://lido.fi",
  },
  {
    id: "gmx",
    name: "GMX",
    symbol: "GMX",
    category: "DEX",
    networks: ["Arbitrum", "Avalanche"],
    tags: ["perps", "dex"],
    lat: 25.2048,
    lng: 55.2708,
    logo: "/protocol-logos/gmx.webp",
    description: "On-chain perpetuals and spot trading liquidity.",
    website: "https://gmx.io",
  },
  {
    id: "comp",
    name: "Compound",
    symbol: "COMP",
    category: "Lending",
    networks: ["Ethereum", "Base"],
    tags: ["lending"],
    lat: 37.7749,
    lng: -122.4194,
    logo: "/protocol-logos/compound.webp",
    description: "Algorithmic money markets for crypto assets.",
    website: "https://compound.finance",
  },
  {
    id: "dydx",
    name: "dYdX",
    symbol: "DYDX",
    category: "DEX",
    networks: ["dYdX Chain"],
    tags: ["perps", "derivatives"],
    lat: 35.6762,
    lng: 139.6503,
    logo: "/protocol-logos/dydx.webp",
    description: "Decentralized derivatives trading infrastructure.",
    website: "https://dydx.exchange",
  },
];

export function formatCoordinate(value: number, axis: "lat" | "lng") {
  const direction =
    axis === "lat" ? (value >= 0 ? "N" : "S") : value >= 0 ? "E" : "W";
  return `${Math.abs(value).toFixed(2)}°${direction}`;
}

export function formatProtocolLocation(protocol: Protocol) {
  return `${formatCoordinate(protocol.lat, "lat")} ${formatCoordinate(
    protocol.lng,
    "lng",
  )}`;
}
